Name: product.rpc
ListenOn: 0.0.0.0:9001
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: product.rpc
Mysql:
  DataSource: root:as1028@tcp(127.0.0.1:3306)/snai_mall?charset=utf8mb4&parseTime=true&loc=Local
CacheRedis:
  - Host: 127.0.0.1:6379
    Pass: as1028
    Type: node
DevServer:
    Enabled: true
    Port: 7091
    MetricsPath: /metrics
Telemetry:
  Name: product.rpc
  Endpoint: http://127.0.0.1:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger